main: games.crusader.javaproject.JavaProjects
#main class package.classname
version: 1.0
author: BigMacMC
name: PrototypePlugin
#one word for name
description: First run at creating a plugin with serveral features

#commands:
# heal:
#  description:
